# Generated by Django 5.2.7 on 2025-11-06 08:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Ism")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=200, verbose_name="Mavzu")),
                ("message", models.TextField(verbose_name="Xabar")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="O'qilgan"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bog'lanish xabari",
                "verbose_name_plural": "Bog'lanish xabarlari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Bo'lim nomi")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="URL slug"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-tooth", max_length=50, verbose_name="Icon class"
                    ),
                ),
                ("description", models.TextField(verbose_name="Qisqa ta'rif")),
                (
                    "full_description",
                    models.TextField(blank=True, verbose_name="To'liq ta'rif"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="departments/",
                        verbose_name="Rasm",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("order", models.IntegerField(default=0, verbose_name="Tartib raqami")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan sana"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bo'lim",
                "verbose_name_plural": "Bo'limlar",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="Savol")),
                ("answer", models.TextField(verbose_name="Javob")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "Umumiy"),
                            ("treatment", "Davolash"),
                            ("appointment", "Qabul"),
                            ("payment", "To'lov"),
                            ("other", "Boshqa"),
                        ],
                        default="general",
                        max_length=100,
                        verbose_name="Kategoriya",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("order", models.IntegerField(default=0, verbose_name="Tartib raqami")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
            ],
            options={
                "verbose_name": "Savol-Javob",
                "verbose_name_plural": "Savol-Javoblar",
                "ordering": ["order", "question"],
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Sarlavha")),
                ("description", models.TextField(blank=True, verbose_name="Ta'rif")),
                ("image", models.ImageField(upload_to="gallery/", verbose_name="Rasm")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Dentist", "Klinika"),
                            ("equipment", "Uskunalar"),
                            ("staff", "Shifokorlar"),
                            ("other", "Boshqa"),
                        ],
                        default="Dentist",
                        max_length=20,
                        verbose_name="Kategoriya",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("order", models.IntegerField(default=0, verbose_name="Tartib raqami")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
            ],
            options={
                "verbose_name": "Galereya rasmi",
                "verbose_name_plural": "Galereya rasmlari",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="DentCare", max_length=200, verbose_name="Sayt nomi"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(blank=True, max_length=500, verbose_name="Shior"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("address", models.TextField(verbose_name="Manzil")),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("telegram", models.URLField(blank=True, verbose_name="Telegram")),
                ("youtube", models.URLField(blank=True, verbose_name="YouTube")),
                (
                    "map_embed",
                    models.TextField(blank=True, verbose_name="Google Maps Embed"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="site/", verbose_name="Logo"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="site/", verbose_name="Favicon"
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(blank=True, verbose_name="Footer matni"),
                ),
            ],
            options={
                "verbose_name": "Sayt sozlamasi",
                "verbose_name_plural": "Sayt sozlamalari",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Ism")),
                (
                    "position",
                    models.CharField(blank=True, max_length=200, verbose_name="Kasb"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Reyting",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Fikr")),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Asosiy sahifada ko'rsatish"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bemor fikri",
                "verbose_name_plural": "Bemor fikrlari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Dushanba"),
                            (1, "Seshanba"),
                            (2, "Chorshanba"),
                            (3, "Payshanba"),
                            (4, "Juma"),
                            (5, "Shanba"),
                            (6, "Yakshanba"),
                        ],
                        unique=True,
                        verbose_name="Kun",
                    ),
                ),
                (
                    "is_working_day",
                    models.BooleanField(default=True, verbose_name="Ish kuni"),
                ),
                (
                    "opening_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Ochilish vaqti"
                    ),
                ),
                (
                    "closing_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Yopilish vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ish vaqti",
                "verbose_name_plural": "Ish vaqtlari",
                "ordering": ["day"],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Shifokor ismi"),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=100, verbose_name="Shifokor familiyasi"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Otasining ismi",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="URL slug"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Erkak"), ("F", "Ayol")],
                        max_length=1,
                        verbose_name="Jinsi",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(max_length=200, verbose_name="Mutaxassislik"),
                ),
                (
                    "degree",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ilmiy daraja"
                    ),
                ),
                (
                    "experience_years",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tajriba yili",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="doctors/", verbose_name="Shifokor rasmi"
                    ),
                ),
                ("bio", models.TextField(verbose_name="Biografiya")),
                ("education", models.TextField(blank=True, verbose_name="Ta'lim")),
                ("achievements", models.TextField(blank=True, verbose_name="Yutuqlar")),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefon raqam +998XXXXXXXXX formatida bo'lishi kerak",
                                regex="^\\+?998\\d{9}$",
                            )
                        ],
                        verbose_name="Telefon raqam",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Reyting",
                    ),
                ),
                (
                    "patients_count",
                    models.IntegerField(
                        default=0, verbose_name="Ko'rilgan bemorlar soni"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Mavjud"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Asosiy"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Tartib raqami")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan sana"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="Dentist.department",
                        verbose_name="Bo'lim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shifokor",
                "verbose_name_plural": "Shifokorlar",
                "ordering": ["order", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Xizmat nomi")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="URL slug"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-tooth", max_length=50, verbose_name="Icon class"
                    ),
                ),
                ("short_description", models.TextField(verbose_name="Qisqa tarif")),
                (
                    "full_description",
                    models.TextField(blank=True, verbose_name="To'liq tarif"),
                ),
                (
                    "price_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Narx dan",
                    ),
                ),
                (
                    "price_to",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Narx gacha",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Davomiyligi (daqiqa)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="Mashhur"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("order", models.IntegerField(default=0, verbose_name="Tartib raqami")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan sana"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="Dentist.department",
                        verbose_name="Bo'lim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat",
                "verbose_name_plural": "Xizmatlar",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="To'liq ism")),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak",
                                regex="^\\+?998\\d{9}$",
                            )
                        ],
                        verbose_name="Telefon",
                    ),
                ),
                ("appointment_date", models.DateField(verbose_name="Qabul sanasi")),
                (
                    "appointment_time",
                    models.TimeField(blank=True, null=True, verbose_name="Qabul vaqti"),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Xabar/Shikoyat"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("confirmed", "Tasdiqlangan"),
                            ("cancelled", "Bekor qilingan"),
                            ("completed", "Yakunlangan"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Admin eslatmalari"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan sana"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="Dentist.department",
                        verbose_name="Bo'lim",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="Dentist.doctor",
                        verbose_name="Shifokor",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="Dentist.service",
                        verbose_name="Xizmat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qabulga yozilish",
                "verbose_name_plural": "Qabulga yozilishlar",
                "ordering": ["-appointment_date", "-created_at"],
            },
        ),
    ]
