# Generated by Django 5.2.8 on 2025-11-08 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ism")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=200, verbose_name="Mavzu")),
                ("message", models.TextField(verbose_name="Xabar")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="O'qilgan"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Xabar",
                "verbose_name_plural": "Kontakt xabarlari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=200, verbose_name="Nomi (UZ)")),
                (
                    "name_ru",
                    models.CharField(max_length=200, verbose_name="Название (RU)"),
                ),
                ("name_en", models.CharField(max_length=200, verbose_name="Name (EN)")),
                ("description_uz", models.TextField(verbose_name="Tavsif (UZ)")),
                ("description_ru", models.TextField(verbose_name="Описание (RU)")),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                (
                    "icon",
                    models.CharField(
                        default="bi bi-activity",
                        max_length=50,
                        verbose_name="Bootstrap Icon",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="departments/",
                        verbose_name="Rasm",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Tartib")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bo'lim",
                "verbose_name_plural": "Bo'limlar",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_uz",
                    models.CharField(max_length=500, verbose_name="Savol (UZ)"),
                ),
                (
                    "question_ru",
                    models.CharField(max_length=500, verbose_name="Вопрос (RU)"),
                ),
                (
                    "question_en",
                    models.CharField(max_length=500, verbose_name="Question (EN)"),
                ),
                ("answer_uz", models.TextField(verbose_name="Javob (UZ)")),
                ("answer_ru", models.TextField(verbose_name="Ответ (RU)")),
                ("answer_en", models.TextField(verbose_name="Answer (EN)")),
                ("order", models.IntegerField(default=0, verbose_name="Tartib")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Savol",
                "verbose_name_plural": "FAQ",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(max_length=200, verbose_name="Sarlavha (UZ)"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=200, verbose_name="Заголовок (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (EN)"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("clinic", "Klinika"),
                            ("equipment", "Jihozlar"),
                            ("team", "Jamoa"),
                            ("patients", "Bemorlar"),
                            ("other", "Boshqa"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Kategoriya",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/", verbose_name="Rasm")),
                ("order", models.IntegerField(default=0, verbose_name="Tartib")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Galereya rasmi",
                "verbose_name_plural": "Galereya",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name_uz",
                    models.CharField(
                        default="DentaCare",
                        max_length=200,
                        verbose_name="Sayt nomi (UZ)",
                    ),
                ),
                (
                    "site_name_ru",
                    models.CharField(
                        default="DentaCare",
                        max_length=200,
                        verbose_name="Название сайта (RU)",
                    ),
                ),
                (
                    "site_name_en",
                    models.CharField(
                        default="DentaCare",
                        max_length=200,
                        verbose_name="Site name (EN)",
                    ),
                ),
                (
                    "tagline_uz",
                    models.CharField(max_length=200, verbose_name="Slogan (UZ)"),
                ),
                (
                    "tagline_ru",
                    models.CharField(max_length=200, verbose_name="Слоган (RU)"),
                ),
                (
                    "tagline_en",
                    models.CharField(max_length=200, verbose_name="Tagline (EN)"),
                ),
                ("about_uz", models.TextField(verbose_name="Biz haqimizda (UZ)")),
                ("about_ru", models.TextField(verbose_name="О нас (RU)")),
                ("about_en", models.TextField(verbose_name="About us (EN)")),
                (
                    "address_uz",
                    models.CharField(max_length=300, verbose_name="Manzil (UZ)"),
                ),
                (
                    "address_ru",
                    models.CharField(max_length=300, verbose_name="Адрес (RU)"),
                ),
                (
                    "address_en",
                    models.CharField(max_length=300, verbose_name="Address (EN)"),
                ),
                ("phone_1", models.CharField(max_length=20, verbose_name="Telefon 1")),
                (
                    "phone_2",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefon 2"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "working_hours_uz",
                    models.CharField(max_length=200, verbose_name="Ish vaqti (UZ)"),
                ),
                (
                    "working_hours_ru",
                    models.CharField(max_length=200, verbose_name="Время работы (RU)"),
                ),
                (
                    "working_hours_en",
                    models.CharField(max_length=200, verbose_name="Working hours (EN)"),
                ),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("twitter", models.URLField(blank=True, verbose_name="Twitter")),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("youtube", models.URLField(blank=True, verbose_name="YouTube")),
                (
                    "google_maps_embed",
                    models.TextField(
                        blank=True, verbose_name="Google Maps iframe kodi"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="settings/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="settings/",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "meta_description_uz",
                    models.TextField(max_length=160, verbose_name="Meta tavsif (UZ)"),
                ),
                (
                    "meta_description_ru",
                    models.TextField(max_length=160, verbose_name="Meta описание (RU)"),
                ),
                (
                    "meta_description_en",
                    models.TextField(
                        max_length=160, verbose_name="Meta description (EN)"
                    ),
                ),
                (
                    "meta_keywords_uz",
                    models.CharField(
                        max_length=300, verbose_name="Meta kalit so'zlar (UZ)"
                    ),
                ),
                (
                    "meta_keywords_ru",
                    models.CharField(
                        max_length=300, verbose_name="Meta ключевые слова (RU)"
                    ),
                ),
                (
                    "meta_keywords_en",
                    models.CharField(max_length=300, verbose_name="Meta keywords (EN)"),
                ),
            ],
            options={
                "verbose_name": "Sayt sozlamasi",
                "verbose_name_plural": "Sayt sozlamalari",
            },
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_uz",
                    models.CharField(max_length=100, verbose_name="Yorliq (UZ)"),
                ),
                (
                    "label_ru",
                    models.CharField(max_length=100, verbose_name="Метка (RU)"),
                ),
                (
                    "label_en",
                    models.CharField(max_length=100, verbose_name="Label (EN)"),
                ),
                ("value", models.IntegerField(verbose_name="Qiymat")),
                (
                    "icon",
                    models.CharField(
                        default="bi bi-award",
                        max_length=50,
                        verbose_name="Bootstrap Icon",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Tartib")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
            ],
            options={
                "verbose_name": "Statistika",
                "verbose_name_plural": "Statistikalar",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ism")),
                (
                    "position_uz",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Lavozim/Kasb (UZ)"
                    ),
                ),
                (
                    "position_ru",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Должность (RU)"
                    ),
                ),
                (
                    "position_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Position (EN)"
                    ),
                ),
                ("text_uz", models.TextField(verbose_name="Fikr (UZ)")),
                ("text_ru", models.TextField(verbose_name="Отзыв (RU)")),
                ("text_en", models.TextField(verbose_name="Review (EN)")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=5,
                        verbose_name="Reyting",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Fikr",
                "verbose_name_plural": "Mijozlar fikrlari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ism")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Familiya"),
                ),
                (
                    "specialty_uz",
                    models.CharField(max_length=200, verbose_name="Mutaxassislik (UZ)"),
                ),
                (
                    "specialty_ru",
                    models.CharField(max_length=200, verbose_name="Специальность (RU)"),
                ),
                (
                    "specialty_en",
                    models.CharField(max_length=200, verbose_name="Specialty (EN)"),
                ),
                ("bio_uz", models.TextField(verbose_name="Biografiya (UZ)")),
                ("bio_ru", models.TextField(verbose_name="Биография (RU)")),
                ("bio_en", models.TextField(verbose_name="Biography (EN)")),
                ("experience_years", models.IntegerField(verbose_name="Tajriba (yil)")),
                ("education_uz", models.TextField(verbose_name="Ta'lim (UZ)")),
                ("education_ru", models.TextField(verbose_name="Образование (RU)")),
                ("education_en", models.TextField(verbose_name="Education (EN)")),
                ("photo", models.ImageField(upload_to="doctors/", verbose_name="Foto")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("twitter", models.URLField(blank=True, verbose_name="Twitter")),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("order", models.IntegerField(default=0, verbose_name="Tartib")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "departments",
                    models.ManyToManyField(
                        related_name="doctors",
                        to="Dentist.department",
                        verbose_name="Bo'limlar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shifokor",
                "verbose_name_plural": "Shifokorlar",
                "ordering": ["order", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=200, verbose_name="Nomi (UZ)")),
                (
                    "name_ru",
                    models.CharField(max_length=200, verbose_name="Название (RU)"),
                ),
                ("name_en", models.CharField(max_length=200, verbose_name="Name (EN)")),
                (
                    "short_description_uz",
                    models.TextField(max_length=300, verbose_name="Qisqa tavsif (UZ)"),
                ),
                (
                    "short_description_ru",
                    models.TextField(
                        max_length=300, verbose_name="Краткое описание (RU)"
                    ),
                ),
                (
                    "short_description_en",
                    models.TextField(
                        max_length=300, verbose_name="Short description (EN)"
                    ),
                ),
                ("description_uz", models.TextField(verbose_name="To'liq tavsif (UZ)")),
                (
                    "description_ru",
                    models.TextField(verbose_name="Полное описание (RU)"),
                ),
                (
                    "description_en",
                    models.TextField(verbose_name="Full description (EN)"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Narx",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Davomiyligi (daqiqa)"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi bi-check-circle",
                        max_length=50,
                        verbose_name="Bootstrap Icon",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="Rasm",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Tartib")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="Dentist.department",
                        verbose_name="Bo'lim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat",
                "verbose_name_plural": "Xizmatlar",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ism Familiya")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("date", models.DateField(verbose_name="Sana")),
                ("time", models.TimeField(verbose_name="Vaqt")),
                ("message", models.TextField(blank=True, verbose_name="Xabar")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("confirmed", "Tasdiqlangan"),
                            ("completed", "Yakunlangan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Admin izohlar"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Dentist.department",
                        verbose_name="Bo'lim",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Dentist.doctor",
                        verbose_name="Shifokor",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Dentist.service",
                        verbose_name="Xizmat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qabul",
                "verbose_name_plural": "Qabulga yozilishlar",
                "ordering": ["-date", "-time"],
            },
        ),
    ]
