# Generated by Django 5.2.8 on 2025-11-08 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dentist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="is_replied",
            field=models.BooleanField(default=False, verbose_name="Javob berilgan"),
        ),
        migrations.AddField(
            model_name="department",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=250, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_featured",
            field=models.BooleanField(
                default=False, verbose_name="Asosiy sahifada ko'rsatish"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=250, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
        ),
        migrations.AddField(
            model_name="service",
            name="is_featured",
            field=models.BooleanField(
                default=False, verbose_name="Asosiy sahifada ko'rsatish"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=250, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ko'rishlar soni"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="is_featured",
            field=models.BooleanField(
                default=False, verbose_name="Asosiy sahifada ko'rsatish"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(db_index=True, verbose_name="Sana"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak",
                        regex="^\\+998\\d{9}$",
                    )
                ],
                verbose_name="Telefon",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Kutilmoqda"),
                    ("confirmed", "Tasdiqlangan"),
                    ("completed", "Yakunlangan"),
                    ("cancelled", "Bekor qilingan"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Holat",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="is_read",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="O'qilgan"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
        ),
        migrations.AlterField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Faol"),
        ),
        migrations.AlterField(
            model_name="department",
            name="order",
            field=models.IntegerField(db_index=True, default=0, verbose_name="Tartib"),
        ),
        migrations.AlterField(
            model_name="department",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="experience_years",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(60),
                ],
                verbose_name="Tajriba (yil)",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Faol"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="order",
            field=models.IntegerField(db_index=True, default=0, verbose_name="Tartib"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak",
                        regex="^\\+998\\d{9}$",
                    )
                ],
                verbose_name="Telefon",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Faol"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="order",
            field=models.IntegerField(db_index=True, default=0, verbose_name="Tartib"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="category",
            field=models.CharField(
                choices=[
                    ("clinic", "Klinika"),
                    ("equipment", "Jihozlar"),
                    ("team", "Jamoa"),
                    ("patients", "Bemorlar"),
                    ("other", "Boshqa"),
                ],
                db_index=True,
                default="other",
                max_length=20,
                verbose_name="Kategoriya",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Faol"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="order",
            field=models.IntegerField(db_index=True, default=0, verbose_name="Tartib"),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(480),
                ],
                verbose_name="Davomiyligi (daqiqa)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Faol"),
        ),
        migrations.AlterField(
            model_name="service",
            name="order",
            field=models.IntegerField(db_index=True, default=0, verbose_name="Tartib"),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Narx",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Faol"),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="order",
            field=models.IntegerField(db_index=True, default=0, verbose_name="Tartib"),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="value",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Qiymat",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Faol"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="rating",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Reyting",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["date", "status"], name="Dentist_app_date_15d874_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["status", "-created_at"], name="Dentist_app_status_81654d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["is_read", "-created_at"], name="Dentist_con_is_read_77011d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["is_active", "order"], name="Dentist_dep_is_acti_007e0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["is_active", "order"], name="Dentist_doc_is_acti_3bbda3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gallery",
            index=models.Index(
                fields=["category", "is_active"], name="Dentist_gal_categor_26ff21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["department", "is_active"],
                name="Dentist_ser_departm_d5eb1d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["is_featured", "is_active"],
                name="Dentist_ser_is_feat_73a0ea_idx",
            ),
        ),
    ]
