# Generated by Django 5.2.9 on 2025-12-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dentist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accreditation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Sertifikat nomi"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="accreditation/", verbose_name="Sertifikat rasmi"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Tartib raqami")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Akkreditatsiya",
                "verbose_name_plural": "Akkreditatsiyalar",
                "ordering": ["order"],
            },
        ),
    ]
