# Generated by Django 5.2.9 on 2025-12-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dentist", "0002_accreditation"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Accreditation",
        ),
    ]
