# Generated by Django 5.2.8 on 2025-11-11 16:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dentist", "0002_contactmessage_is_replied_department_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "ordering": ["-date", "-time"],
                "verbose_name": "Qabul",
                "verbose_name_plural": "Qabullar",
            },
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Xabar",
                "verbose_name_plural": "Xabarlar",
            },
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
            },
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Galereya rasmi",
                "verbose_name_plural": "Galereya rasmlari",
            },
        ),
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "Sayt sozlamalari",
                "verbose_name_plural": "Sayt sozlamalari",
            },
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Fikr",
                "verbose_name_plural": "Fikrlar",
            },
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="Dentist_app_date_15d874_idx",
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="Dentist_app_status_81654d_idx",
        ),
        migrations.RemoveIndex(
            model_name="doctor",
            name="Dentist_doc_is_acti_3bbda3_idx",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="admin_notes",
            field=models.TextField(blank=True, verbose_name="Admin izohi"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(verbose_name="Sana"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="Dentist.department",
                verbose_name="Bo'lim",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="Dentist.doctor",
                verbose_name="Shifokor",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Ism"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="Dentist.service",
                verbose_name="Xizmat",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan"),
        ),
        migrations.AlterField(
            model_name="department",
            name="description_en",
            field=models.TextField(verbose_name="Description (English)"),
        ),
        migrations.AlterField(
            model_name="department",
            name="description_ru",
            field=models.TextField(verbose_name="Описание (Русский)"),
        ),
        migrations.AlterField(
            model_name="department",
            name="description_uz",
            field=models.TextField(verbose_name="Ta'rif (O'zbek)"),
        ),
        migrations.AlterField(
            model_name="department",
            name="icon",
            field=models.CharField(
                default="bi bi-hospital",
                help_text="Bootstrap icon class nomi",
                max_length=100,
                verbose_name="Icon class",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Ruxsat etilgan formatlar: JPG, PNG, WEBP",
                null=True,
                upload_to="departments/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="Rasm",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name_en",
            field=models.CharField(max_length=200, verbose_name="Name (English)"),
        ),
        migrations.AlterField(
            model_name="department",
            name="name_ru",
            field=models.CharField(max_length=200, verbose_name="Название (Русский)"),
        ),
        migrations.AlterField(
            model_name="department",
            name="name_uz",
            field=models.CharField(max_length=200, verbose_name="Nomi (O'zbek)"),
        ),
        migrations.AlterField(
            model_name="department",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Tartib"),
        ),
        migrations.AlterField(
            model_name="department",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="bio_en",
            field=models.TextField(verbose_name="Biography (English)"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="bio_ru",
            field=models.TextField(verbose_name="Биография (Русский)"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="bio_uz",
            field=models.TextField(verbose_name="Biografiya (O'zbek)"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="education_en",
            field=models.TextField(blank=True, verbose_name="Education (English)"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="education_ru",
            field=models.TextField(blank=True, verbose_name="Образование (Русский)"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="education_uz",
            field=models.TextField(blank=True, verbose_name="Ta'lim (O'zbek)"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="experience_years",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(50)],
                verbose_name="Tajriba (yil)",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="is_featured",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Asosiyda ko'rsatish"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Tartib"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="doctors/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="Fotosurat",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialty_en",
            field=models.CharField(max_length=200, verbose_name="Specialty (English)"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialty_ru",
            field=models.CharField(
                max_length=200, verbose_name="Специальность (Русский)"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialty_uz",
            field=models.CharField(
                max_length=200, verbose_name="Mutaxassisligi (O'zbek)"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer_en",
            field=models.TextField(verbose_name="Answer (English)"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer_ru",
            field=models.TextField(verbose_name="Ответ (Русский)"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer_uz",
            field=models.TextField(verbose_name="Javob (O'zbek)"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Tartib"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_en",
            field=models.CharField(max_length=500, verbose_name="Question (English)"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_ru",
            field=models.CharField(max_length=500, verbose_name="Вопрос (Русский)"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_uz",
            field=models.CharField(max_length=500, verbose_name="Savol (O'zbek)"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(
                upload_to="gallery/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="Rasm",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Tartib"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="title_en",
            field=models.CharField(max_length=200, verbose_name="Title (English)"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="title_ru",
            field=models.CharField(max_length=200, verbose_name="Заголовок (Русский)"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="title_uz",
            field=models.CharField(max_length=200, verbose_name="Sarlavha (O'zbek)"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description_en",
            field=models.TextField(verbose_name="Full description (English)"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description_ru",
            field=models.TextField(verbose_name="Полное описание (Русский)"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description_uz",
            field=models.TextField(verbose_name="To'liq ta'rif (O'zbek)"),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(480),
                ],
                verbose_name="Davomiyligi (daqiqa)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.CharField(
                default="bi bi-heart-pulse", max_length=100, verbose_name="Icon class"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="services/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="Rasm",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_featured",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Asosiyda ko'rsatish"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name_en",
            field=models.CharField(max_length=200, verbose_name="Name (English)"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name_ru",
            field=models.CharField(max_length=200, verbose_name="Название (Русский)"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name_uz",
            field=models.CharField(max_length=200, verbose_name="Nomi (O'zbek)"),
        ),
        migrations.AlterField(
            model_name="service",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Tartib"),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Narxi",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="short_description_en",
            field=models.CharField(
                max_length=300, verbose_name="Short description (English)"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="short_description_ru",
            field=models.CharField(
                max_length=300, verbose_name="Краткое описание (Русский)"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="short_description_uz",
            field=models.CharField(
                max_length=300, verbose_name="Qisqa ta'rif (O'zbek)"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan"),
        ),
        migrations.AlterField(
            model_name="service",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rilgan"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="about_en",
            field=models.TextField(blank=True, verbose_name="About us (English)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="about_ru",
            field=models.TextField(blank=True, verbose_name="О нас (Русский)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="about_uz",
            field=models.TextField(blank=True, verbose_name="Biz haqimizda (O'zbek)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="address_en",
            field=models.CharField(max_length=500, verbose_name="Address (English)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="address_ru",
            field=models.CharField(max_length=500, verbose_name="Адрес (Русский)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="address_uz",
            field=models.CharField(max_length=500, verbose_name="Manzil (O'zbek)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site/",
                validators=[
                    django.core.validators.FileExtensionValidator(["ico", "png"])
                ],
                verbose_name="Favicon",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="google_maps_embed",
            field=models.TextField(blank=True, verbose_name="Google Maps embed kodi"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "svg", "webp"]
                    )
                ],
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_description_en",
            field=models.TextField(
                blank=True, max_length=160, verbose_name="Meta Description (English)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_description_ru",
            field=models.TextField(
                blank=True, max_length=160, verbose_name="Meta Description (Русский)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_description_uz",
            field=models.TextField(
                blank=True, max_length=160, verbose_name="Meta Description (O'zbek)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_keywords_en",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Meta Keywords (English)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_keywords_ru",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Meta Keywords (Русский)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_keywords_uz",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Meta Keywords (O'zbek)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name_en",
            field=models.CharField(
                default="MediNest", max_length=200, verbose_name="Site name (English)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name_ru",
            field=models.CharField(
                default="MediNest",
                max_length=200,
                verbose_name="Название сайта (Русский)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name_uz",
            field=models.CharField(
                default="MediNest", max_length=200, verbose_name="Sayt nomi (O'zbek)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="tagline_en",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Tagline (English)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="tagline_ru",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Слоган (Русский)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="tagline_uz",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Slogan (O'zbek)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_en",
            field=models.CharField(
                default="Mon-Fri: 09:00-20:00",
                max_length=200,
                verbose_name="Working hours (English)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_ru",
            field=models.CharField(
                default="Пн-Пт: 09:00-20:00",
                max_length=200,
                verbose_name="Часы работы (Русский)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_uz",
            field=models.CharField(
                default="Dush-Juma: 09:00-20:00",
                max_length=200,
                verbose_name="Ish vaqti (O'zbek)",
            ),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="icon",
            field=models.CharField(
                default="bi bi-heart", max_length=100, verbose_name="Icon class"
            ),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="label_en",
            field=models.CharField(max_length=200, verbose_name="Label (English)"),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="label_ru",
            field=models.CharField(max_length=200, verbose_name="Название (Русский)"),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="label_uz",
            field=models.CharField(max_length=200, verbose_name="Nomi (O'zbek)"),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Tartib"),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="value",
            field=models.PositiveIntegerField(default=0, verbose_name="Qiymat"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="is_featured",
            field=models.BooleanField(
                default=False, verbose_name="Asosiyda ko'rsatish"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="testimonials/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="Fotosurat",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="position_en",
            field=models.CharField(max_length=200, verbose_name="Position (English)"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="position_ru",
            field=models.CharField(max_length=200, verbose_name="Должность (Русский)"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="position_uz",
            field=models.CharField(
                max_length=200, verbose_name="Lavozim/Kasb (O'zbek)"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="rating",
            field=models.IntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Reyting",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="text_en",
            field=models.TextField(verbose_name="Testimonial (English)"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="text_ru",
            field=models.TextField(verbose_name="Отзыв (Русский)"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="text_uz",
            field=models.TextField(verbose_name="Fikr (O'zbek)"),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("doctor", "date", "time")},
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["status", "date"], name="Dentist_app_status_0a7d53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "date", "time"], name="Dentist_app_doctor__4dd4fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["slug"], name="Dentist_dep_slug_4d5529_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["-created_at"], name="Dentist_dep_created_8787c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(fields=["slug"], name="Dentist_doc_slug_6c4257_idx"),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="Dentist_doc_is_acti_89dd20_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["slug"], name="Dentist_ser_slug_509a32_idx"),
        ),
        migrations.AddIndex(
            model_name="testimonial",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="Dentist_tes_is_acti_91f031_idx",
            ),
        ),
    ]
