# Generated by Django 5.2.9 on 2025-12-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dentist", "0003_about_delete_accreditation"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="chief_doctor_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="settings/",
                verbose_name="Bosh shifokor rasmi",
            ),
        ),
    ]
