# Generated by Django 5.2.9 on 2025-12-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dentist", "0004_sitesettings_chief_doctor_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="patients_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ko'rilgan bemorlar soni"
            ),
        ),
    ]
