# Generated by Django 5.2.9 on 2025-12-24 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dentist", "0005_alter_doctor_patients_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="consultation_duration",
            field=models.PositiveIntegerField(
                default=30, verbose_name="Ko'rik davomiyligi (minut)"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_fri",
            field=models.BooleanField(default=True, verbose_name="Ju"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_mon",
            field=models.BooleanField(default=True, verbose_name="Du"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_sat",
            field=models.BooleanField(default=False, verbose_name="Sha"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_sun",
            field=models.BooleanField(default=False, verbose_name="Yak"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_thu",
            field=models.BooleanField(default=True, verbose_name="Pay"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_tue",
            field=models.BooleanField(default=True, verbose_name="Se"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_wed",
            field=models.BooleanField(default=True, verbose_name="Chor"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="work_end",
            field=models.TimeField(default="18:00", verbose_name="Ish tugash vaqti"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="work_start",
            field=models.TimeField(default="09:00", verbose_name="Ish boshlash vaqti"),
        ),
        migrations.CreateModel(
            name="DoctorLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Sana")),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, verbose_name="Sababi"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="Dentist.doctor",
                        verbose_name="Shifokor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dam olish kuni",
                "verbose_name_plural": "Dam olish kunlari",
            },
        ),
    ]
