# Generated by Django 5.2.9 on 2025-12-25 08:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dentist", "0006_doctor_consultation_duration_doctor_is_fri_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={
                "verbose_name": "Biz haqimizda",
                "verbose_name_plural": "Biz haqimizda",
            },
        ),
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "ordering": ["-appointment_date", "-created_at"],
                "verbose_name": "Qabul",
                "verbose_name_plural": "Qabullar",
            },
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Xabar",
                "verbose_name_plural": "Xabarlar",
            },
        ),
        migrations.AlterModelOptions(
            name="doctorleave",
            options={
                "ordering": ["-date"],
                "verbose_name": "Dam olish kuni",
                "verbose_name_plural": "Dam olish kunlari",
            },
        ),
        migrations.AlterModelOptions(
            name="galleryimage",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Galereya rasmi",
                "verbose_name_plural": "Galereya",
            },
        ),
        migrations.AlterModelOptions(
            name="sitesettings",
            options={"verbose_name": "Sozlama", "verbose_name_plural": "Sozlamalar"},
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Fikr",
                "verbose_name_plural": "Fikrlar",
            },
        ),
        migrations.AlterField(
            model_name="about",
            name="description",
            field=models.TextField(verbose_name="Ta'rif"),
        ),
        migrations.AlterField(
            model_name="about",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Sarlavha"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="message",
            field=models.TextField(blank=True, verbose_name="Xabar"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefon +998XXXXXXXXX formatida bo'lishi kerak",
                        regex="^\\+?998\\d{9}$",
                    )
                ],
                verbose_name="Telefon",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
        ),
        migrations.AlterField(
            model_name="department",
            name="icon",
            field=models.CharField(
                default="fas fa-tooth",
                help_text="FontAwesome icon class",
                max_length=50,
                verbose_name="Icon class",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Ko'rsatish tartibi (kichik raqam birinchi)",
                verbose_name="Tartib raqami",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="consultation_duration",
            field=models.PositiveIntegerField(
                default=30, verbose_name="Konsultatsiya davomiyligi (daqiqa)"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Ism"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Asosiy sahifada"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="is_fri",
            field=models.BooleanField(default=True, verbose_name="Juma"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="is_mon",
            field=models.BooleanField(default=True, verbose_name="Dushanba"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="is_sat",
            field=models.BooleanField(default=False, verbose_name="Shanba"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="is_sun",
            field=models.BooleanField(default=False, verbose_name="Yakshanba"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="is_thu",
            field=models.BooleanField(default=True, verbose_name="Payshanba"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="is_tue",
            field=models.BooleanField(default=True, verbose_name="Seshanba"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="is_wed",
            field=models.BooleanField(default=True, verbose_name="Chorshanba"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Familiya"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="patients_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Bemorlar soni"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefon +998XXXXXXXXX formatida bo'lishi kerak",
                        regex="^\\+?998\\d{9}$",
                    )
                ],
                verbose_name="Telefon",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="photo",
            field=models.ImageField(upload_to="doctors/", verbose_name="Rasm"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
        ),
        migrations.AlterField(
            model_name="doctorleave",
            name="reason",
            field=models.CharField(blank=True, max_length=255, verbose_name="Sabab"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Tartib"),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="category",
            field=models.CharField(
                choices=[
                    ("clinic", "Klinika"),
                    ("equipment", "Uskunalar"),
                    ("staff", "Shifokorlar"),
                    ("other", "Boshqa"),
                ],
                default="clinic",
                max_length=20,
                verbose_name="Kategoriya",
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Tartib"),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
        ),
        migrations.AlterField(
            model_name="service",
            name="full_description",
            field=models.TextField(blank=True, verbose_name="To'liq ta'rif"),
        ),
        migrations.AlterField(
            model_name="service",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Tartib"),
        ),
        migrations.AlterField(
            model_name="service",
            name="price_from",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Narx (dan)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="price_to",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Narx (gacha)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="short_description",
            field=models.TextField(verbose_name="Qisqa ta'rif"),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_text",
            field=models.TextField(blank=True, verbose_name="Footer"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="map_embed",
            field=models.TextField(blank=True, verbose_name="Google Maps"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Asosiy sahifa"),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="closing_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Yopilish"),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="opening_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Ochilish"),
        ),
        migrations.AlterUniqueTogether(
            name="doctorleave",
            unique_together={("doctor", "date")},
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["status", "appointment_date"],
                name="Dentist_app_status_73b16e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "appointment_date"],
                name="Dentist_app_doctor__305c79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["slug"], name="Dentist_dep_slug_4d5529_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["is_active", "order"], name="Dentist_dep_is_acti_007e0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(fields=["slug"], name="Dentist_doc_slug_6c4257_idx"),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["is_available", "is_featured"],
                name="Dentist_doc_is_avai_17c7a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["department", "is_available"],
                name="Dentist_doc_departm_5662cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["slug"], name="Dentist_ser_slug_509a32_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["is_active", "is_popular"],
                name="Dentist_ser_is_acti_2805fb_idx",
            ),
        ),
    ]
