# Generated by Django 5.2.9 on 2025-12-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dentist", "0007_alter_about_options_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(
                default="+998", max_length=20, verbose_name="Telefon"
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
    ]
